version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies.....
      - npm install

  build:
    commands:
      - echo Building Next.js app...
      - npm run build

  post_build:
    commands:
      - echo Deploying and starting app on EC2 via SSM...
      - |
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=tag:Name,Values=WindowsInstance" \
          --comment "Deploy and Start Next.js App" \
          --parameters '{"commands":["cd C:\\\\Users\\\\Administrator\\\\nextjs-app","git pull","npm install -g pm2","npm install","npm run build","pm2 stop all","pm2 start npm --name nextjs-app -- run start","pm2 save"]}' \
          --region us-east-1 \
          --output text

artifacts:
  files:
    - '**/*'
