version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building the app
      - npm run build
  post_build:
    commands:
      - echo Deploying via SSM...
      - |
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --region us-east-1 \
          --instance-ids i-000d880214e5629a2 \
          --comment "Deploy Next.js App" \
          --parameters '{"commands":["cd C:\\\\Users\\\\Administrator\\\\nextjs-app","git pull","npm install","npm run build","pm2 restart all"]}' \
          --output text

artifacts:
  files:
    - '**/*'
  base-directory: .next
