# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building Next.js app...
      - npm run build

  post_build:
    commands:
      - echo Logging into EC2 via SSM...
      - aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=tag:Name,Values=WindowsInstance" \
          --comment "Deploy Next.js App" \
          --parameters 'commands=["cd C:\\Users\\Administrator\\nextjs-app","git pull","npm install","npm run build","npm run start"]' \
          --region 'us-east-1'

artifacts:
  files:
    - '**/*'
