version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building the Next.js application...
      - npm run build

  post_build:
    commands:
      - echo Deploying to EC2 via SSM
      - |
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=tag:Name,Values=WindowsInstance" \
          --comment "Trigger Next.js Deployment" \
          --parameters commands=["cd C:\\Users\\Administrator\\nextjs-app", "git pull", "npm install", "npm run build", "pm2 restart nextjs-app"] \
          --region YOUR_AWS_REGION

artifacts:
  files:
    - '**/*'
  base-directory: .next
