version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building the Next.js app..."
      - npm run build
      - echo "Packaging build for EC2 upload (manual or scripted)..."
      - mkdir -p packaged
      - test -f package.json || (echo "Missing package.json" && exit 1)
      - test -f Procfile || (echo "Missing Procfile" && exit 1)
      - zip -r nextjs-app.zip package.json .next node_modules pages public next.config.js Procfile

  post_build:
    commands:
      - echo "Deploying to Windows EC2 via SSM..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=tag:Name,Values=WindowsInstance" \
          --comment "Deploy Next.js app from local zip" \
          --parameters '{"commands":[
              "cd C:\\Users\\Administrator",
              "if (Test-Path nextjs-app) { Remove-Item -Recurse -Force nextjs-app }",
              "Expand-Archive -Path nextjs-app.zip -DestinationPath nextjs-app -Force",
              "cd nextjs-app",
              "npm install -g pm2",
              "npm ci",
              "npm run build",
              "pm2 stop all",
              "pm2 start npm --name nextjs-app -- run start",
              "pm2 save"
          ]}' \
          --region us-east-1 \
          --output text

artifacts:
  files:
    - nextjs-app.zip