version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=YOUR_INSTANCE_ID" \
          --parameters "commands=[ 'cd /home/ec2-user/app', 'git pull', 'npm install', 'npm run build', 'pm2 restart all' ]" \
          --region YOUR_REGION

artifacts:
  files:
    - '**/*'
