version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "CodeBuild install phase complete"
      - npm ci
  build:
    commands:
      - echo "Skipping CodeBuild build step"
      - npm run build

  post_build:
    commands:
      - echo "Triggering SSM command to EC2..."
      - |
        aws ssm send-command \
          --document-name "AWS-RunPowerShellScript" \
          --targets "Key=tag:Name,Values=WindowsInstance" \
          --comment "Trigger Next.js build on EC2" \
          --parameters '{"commands":[
              "cd C:\\Users\\Administrator\\nextjs-app",
              "git reset --hard",
              "git pull origin main",
              "npm install -g pm2",
              "npm ci",
              "npm run build",
              "pm2 stop all",
              "pm2 start npm --name nextjs-app -- run start",
              "pm2 save"
          ]}' \
          --region us-east-1 \
          --output text

artifacts:
  files:
    - '**/*'
  base-directory: '.next'   # Change to 'out' if you use next export
  discard-paths: yes
